spring.application.name=shelfd
spring.datasource.url=jdbc:postgresql://localhost:5432/your_db
spring.datasource.username=julliana
spring.datasource.password=pass123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true